### ISSUE TITLE
Some problems of raw data collected with rosbag

### ISSUE THREAD

**Issue by wkentaro** [furushchev/jsk_semantics_201607#3]
## Problems
- [x] Very similar images (problem for evaluation)
- [x] Wrongly labeled data because of PR2's moving
- [x] Wrongly labeled data because of occlusion
### Very similar images

It seems easy to segment very similar images at testing stage after training,
so this makes it difficult to evaluate the model precisely.
#### Possible solutions
1. See the world coords of camera link in rosbag and save data only it is changed.
2. Collect data online after some moving.

**Example**
<img src="https://cloud.githubusercontent.com/assets/4310419/16870020/8ecf3cd2-4aba-11e6-9a77-3879a3e40548.png" width="40%" /> <img src="https://cloud.githubusercontent.com/assets/4310419/16870026/935d6e4a-4aba-11e6-9ab3-98d3cbd33fc4.png" width="40%" />

https://drive.google.com/drive/u/1/folders/0B9P1L--7Wd2vdDZYVlVzZF9RbDA
#### Possible solutions
1. See the world velocity of camera link in rosbag and save data only it is changed.
2. Collect data online after some moving.

<img src="https://cloud.githubusercontent.com/assets/4310419/16870155/1163c096-4abb-11e6-9393-dfb79a1b68fc.png" width="40%" /> <img src="https://cloud.githubusercontent.com/assets/4310419/16870143/0578f92c-4abb-11e6-8c22-c96fad20cd28.png" width="40%" />
### Wrongly labeled data because of occlusion

@furushchev Possible to remove labeling in the region of occlusion?

<img src="https://cloud.githubusercontent.com/assets/4310419/16870216/70f2a25c-4abb-11e6-89fb-3e8da52880d7.png" width="40%" /> <img src="https://cloud.githubusercontent.com/assets/4310419/16870217/70f72174-4abb-11e6-946b-007363be4d03.png" width="40%" />

**Comment by wkentaro** [comment]
@furushchev Let's discuss about these problems whether they are solvable with your stage (chapter3) or my stage (chapter4).

**Comment by furushchev** [comment]
@wkentaro Thanks for analyzing image data.

Here is my idea.
- Very similar images
  - (As workaround) avoid to use similar class
  - (Essentially) I will be able to solve this problem by counting conditional joint probability of the result of recognition with other classes.
- Wrongly labeled data because of PR2's moving
  - How about filtering by whether the velocity of robot is under a threshold?
  - Pose of robot in euslisp is from `tf`, and it provides latest solvable time, so I'm now working on publishing mask image with latest time that `tf` is solved. I think it solve the lag between camera image and processed image. But need to retake bag data.
- Wrongly labeled data because of occlusion
  - Actually does it matter? I think in the situation of local detection, it does not matter even if another object is in masked images, because images are also supposed to be occluded in running (not learning) phase.
  - publishing mask image without occluding region needs higher computational cost because all objects between robot and target object need to be rendered, I think.

**Comment by wkentaro** [comment]
> (As workaround) avoid to use similar class

What is **class**? The reason why there are very similar images is the publish-mask-image.l does publish mask image without considering the move of camera link. It publishes as many as possible.

> How about filtering by whether the velocity of robot is under a threshold?

How can I do that? Which topic should I take and what the velocity?
I suppose you mean the velocity of camera_link.

> Actually does it matter? I think in the situation of local detection, it does not matter even if another object is in masked images, because images are also supposed to be occluded in running (not learning) phase.

I think it does matter, because with current approach, the mask is generated even if the target object is completely occluded, isn't it? For example, if PR2 looks at the direction of refrigerator from my desk at data collection status, he thinks the Kiva Shelf is the refrigerator, doesn't he?

> publishing mask image without occluding region needs higher computational cost because all objects between robot and target object need to be rendered, I think.

Maybe you can use point cloud that is published by Kinect sensor.
There are two approaches:
1. Publish euslisp model, and generate mask of region where the point cloud and euslisp model overlap (maybe with C++ robot self filter node).
2. Subscribe point cloud and generate mask of region where the point cloud and euslisp mdoel overlap (in euslisp node).

**Comment by furushchev** [comment]
> What is class? The reason why there are very similar images is the publish-mask-image.l does publish mask image without considering the move of camera link. It publishes as many as possible.

Oh, sorry i misunderstood.
Well, what is `evaluate` you mean?

> How can I do that? Which topic should I take and what the velocity? I suppose you mean the velocity of camera_link.

we can use `tf` from `/world` to `/head_mount_kinect_rgb_optical_frame`.

> I think it does matter, because with current approach, the mask is generated even if the target object is completely occluded, isn't it? For example, if PR2 looks at the direction of refrigerator from my desk at data collection status, he thinks the Kiva Shelf is the refrigerator, doesn't he?

You are correct.
- With euslisp, it is easy to compute how many points from point clouds are in the model surface, which I think we can use the model is occluded or not.
- Another possible approach is to use object consistency. e.g. compare image and model color ambiguously, or compare expected duplicated region of images from other directions.

**Comment by wkentaro** [comment]
> Oh, sorry i misunderstood.
> Well, what is evaluate you mean?

I mean the accuracy in train/test status for deep neural network.
If there are many very similar images
1. We cannot use **random** to split dataset to train and test one for evaluation of the segmentation network model. (because if similar images are mixed in train and test dataset, the result of evaluation is unreliable).
2. The mean value of accuracy becomes inaccurate.

> we can use tf from /world to /head_mount_kinect_rgb_optical_frame.

I see. That is possible.

> You are correct.
> With euslisp, it is easy to compute how many points from point clouds are in the model surface, which I think we can use the model is occluded or not.
> Another possible approach is to use object consistency. e.g. compare image and model color ambiguously, or compare expected duplicated region of images from other directions.

~~Why not [RobotToMaskImage](http://jsk-docs.readthedocs.io/en/latest/jsk_recognition/doc/jsk_perception/nodes/robot_to_mask_image.html)?~~
Oops, the RobotToMaskImage does nothing but convert robot to mask image without consideration of point cloud.
But maybe you can use below pipeline:

euslisp model -> robot_description -> [robot_self_filter](https://github.com/PR2/robot_self_filter) -> filtered point cloud -> [OrganizedPointCloudToPointIndices](http://jsk-docs.readthedocs.io/en/latest/jsk_recognition/doc/jsk_pcl_ros/nodes/organized_point_cloud_to_point_indices.html) -> [PointIndicesToMaskImage](http://jsk-docs.readthedocs.io/en/latest/jsk_recognition/doc/jsk_pcl_ros_utils/nodes/point_indices_to_mask_image.html).

**Comment by furushchev** [comment]
> I mean the accuracy in train/test status for deep neural network.

I see. How about filtering with time and absolute position of camera link from world?

**Comment by wkentaro** [comment]
> I see. How about filtering with time and absolute position of camera link from world?

Yeah, I will do that.

**Comment by furushchev** [comment]
> euslisp model -> robot_description -> robot_self_filter -> filtered point cloud -> OrganizedPointCloudToPointIndices -> PointIndicesToMaskImage.

I'm now working on this.

maybe actual route will be

eus model -> bounding box -> attention clipper -> filtered cloud -> indices -> mask

compiling latest self_filter and jsk_pcl_ros on hydro is really tough...

**Comment by wkentaro** [comment]
> compiling latest self_filter 

I think @mmurooka uses it and he can help you.

> jsk_pcl_ros on hydro is really tough...

I'm wondering why, because the travis testing has passed.
https://travis-ci.org/jsk-ros-pkg/jsk_recognition/builds/145303717

**Comment by wkentaro** [comment]
Closed via #7
